### ISSUE TITLE
Output filled with logging when writing tasks

### ISSUE THREAD

**Issue by deiga** [rupisaini/vscode-ansible-linter#1]
```
[Error - 14:42:15] Request textDocument/completion failed.
  Message: Unhandled method textDocument/completion
  Code: -32601 
```

**Comment by rupisaini** [comment]
Hi Timo,
Can you please send me bit more details about your environment i.e. OS and
python package etc

**Comment by deiga** [comment]
macOS 10.13.2
ansible-lint 3.4.20
pip 9.0.1

**Comment by rupisaini** [comment]
I tested this extension on both Ubuntu and Mac. It seems to be working
fine. Try again after installing
https://marketplace.visualstudio.com/items?itemName=haaaad.ansible
extension.
