### ISSUE TITLE
The plugin doesn't work

### ISSUE THREAD

**Issue by dmitryzykov** [rupisaini/vscode-ansible-linter#2]
I'm using latest stable VS Code
Version 1.22.1
with vscode-ansible-linter 0.4.0
ansible-lint 3.4.21 is installed.
The latest Mac OS X 

but there is no any linter output in VS Code from this plugin.

If I run ansible-lint manually on the console it shows that there are some errors. But in Code nothing. 
<img width="1152" alt="screen shot 2018-04-10 at 5 56 35 pm" src="https://user-images.githubusercontent.com/15911918/38565155-45a60da6-3ce9-11e8-9452-9412652625a4.png">

**Comment by rupisaini** [comment]
was it working for you with earlier version of VSCode? Can you please also
provide error from using developer tool (
https://code.visualstudio.com/docs/extensions/developing-extensions#_developer-tools-console
)?

**Comment by rupisaini** [comment]
You also need to change file format type to Ansible, looks like you are
using YAML format.

**Comment by dmitryzykov** [comment]
>was it working for you with earlier version of VSCode? 

I haven't tried it before.

>Can you please also provide error from using developer tool

I can't see any related to ansible-linter messages in developer tools log. 

>You also need to change file format type to Ansible, looks like you are
using YAML format.

I'm using `Ansible` extension by Microsoft and it doesn't provide Ansible format, it works under YAML.

Does ansible-linter require `language-Ansible` extension (which provide ansible format)?

**Comment by rupisaini** [comment]
At the moment plugin only get triggered if file type is ansible so you need
to install language-Ansible. I will try to test it with YAML format in next
version.

**Comment by rupisaini** [comment]
Changed the extension to work with YAML format as well.

**Comment by dmitryzykov** [comment]
Thank you. Now it works well!
