### ISSUE TITLE
Doesn't work with space in path to file

### ISSUE THREAD

**Issue by dmitryzykov** [rupisaini/vscode-ansible-linter#4]
When a path to yaml file contains space linter plugin doesn't work.
For example when I keep yaml files in Google Drive:
`/Users/dmitry/Google Drive/ansible/`

I'm using latest stable VS Code
Version 1.22.2
with vscode-ansible-linter 0.8.0
ansible-lint 3.4.21 is installed.
The latest Mac OS X

<img width="1152" alt="screen shot 2018-04-19 at 7 20 20 pm" src="https://user-images.githubusercontent.com/15911918/39004812-16f0e9ac-4407-11e8-8131-7829a41e944d.png">

**Comment by rupisaini** [comment]
Fixed, check latest version

**Comment by dmitryzykov** [comment]
Thank you. Now it works well!
