### ISSUE TITLE
The output panel is displayed almost each time you type

### ISSUE THREAD

**Issue by in-in** [rupisaini/vscode-ansible-linter#5]
The error message:
>Message: Unhandled method textDocument/completion
Code: -32601

And it's annoying, because this panel sometimes covers the code
![18060701](https://user-images.githubusercontent.com/8797432/41098739-225e2b0e-6a65-11e8-84a5-1b4a46bfc9ab.png)

**rupisaini.vscode-ansible-linter**:
Version 0.9.0

**Visual Studio Code**:
Version 1.24.0
Commit 6a6e02cef0f2122ee1469765b704faf5d0e0d859
Date 2018-06-06T17:37:01.579Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**ansible-lint --version**
ansible-lint 3.4.21

**pip --version**
pip 10.0.1 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)

**Ubuntu 18.04 LTS**:
OS type 64-bit

![lint](https://user-images.githubusercontent.com/8797432/41100856-0f3a3b8e-6a6b-11e8-867b-1b0f5ddde4ba.gif)

If `vscode-ansible-linter` is disabled, the error does not occur

**Comment by rupisaini** [comment]
try to change *files.autoSave* of vscode under settings (what is your
current auto save settings?)

**Comment by in-in** [comment]
I'm don't use _autoSave_
`"files.autoSave": "off"`

I even explicitly added `"files.autoSave": "off"` to my file _user-settings.json_
Nothing changed

**Comment by sawyers** [comment]
Once I set "python.unitTest.autoTestDiscoverOnSaveEnabled" to false I stopped getting the message.  It may not be the best answer, but it's something

**Comment by sawyers** [comment]
A different plugin had the same error, they fixed it with this commit...

https://github.com/ly95/vsc.phpmd/commit/166a19d6afbda619fa408717ae46e93974a5742f

Your mileage may differ

**Comment by rupisaini** [comment]
Hi Michael,

Thanks for providing the fix. I am not sure why I I set
completionProvider (may be not reading documentation carefully enough :) )
> I have pushed the version 0.11.0 with fix.
