### ISSUE TITLE
Problems do not clear when .yml file is closed

### ISSUE THREAD

**Issue by mlgann** [rupisaini/vscode-ansible-linter#6]
When you open a .yml file, the linter correctly displays the files problems in the Problems pane.  However, upon closing the file, the problems remain displayed.  As you open and close more files, the problem list continually grows and there is no way to "remove" the displayed problems without closing and re-opening the VSCode app.

Using latest version of VSCode and vscode-ansible-linter on July 11th 2018.

**Comment by rupisaini** [comment]
I just fixed the issue, please check Version 0.10.0
